# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-28 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(to='api_users.Deck'),
        ),
        migrations.AddField(
            model_name='deck',
            name='commander',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api_users.Card'),
        ),
    ]
