# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0004_ligue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='ligues',
            field=models.ManyToManyField(to='api_users.Ligue'),
        ),
        migrations.AddField(
            model_name='scores',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_users.Deck'),
        ),
        migrations.AddField(
            model_name='scores',
            name='ligue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_users.Ligue'),
        ),
    ]
