# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0005_auto_20190516_1715'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scores',
            new_name='Score',
        ),
    ]
