# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0006_auto_20190516_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligue',
            name='users',
        ),
        migrations.AddField(
            model_name='ligue',
            name='decks',
            field=models.ManyToManyField(to='api_users.Deck'),
        ),
        migrations.AlterField(
            model_name='card',
            name='decks',
            field=models.ManyToManyField(blank=True, default=None, to='api_users.Deck'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='ligues',
            field=models.ManyToManyField(blank=True, default=None, to='api_users.Ligue'),
        ),
    ]
