# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0011_auto_20190518_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='decks',
        ),
    ]
