# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-21 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0012_remove_card_decks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='commander',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commander', to='api_users.Card'),
        ),
    ]
