# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0013_auto_20190521_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deckcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='deck',
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api_users.Deck'),
        ),
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='DeckCard',
        ),
    ]
